### ISSUE TITLE
Support editing in UTC timezone

### ISSUE THREAD

**Issue by cdhowie** [eight04/angular-datetime#13]
We have a use case where the date value needs to be displayed to the user and editable by the user in the UTC timezone, not in the user's local timezone. An option to enable this behavior would be very useful.

**Comment by eight04** [comment]
Sounds good. We can put the transition in `$parser` and `$formatter`.

BTW, how do you create the date object? It is a interesting use case.

**Comment by eight04** [comment]
I found this when looking around MDN

* `input[type=datetime]` has been removed from WHATWG HTML: whatwg/html#336

Seems that `type=datetime` will be in local timezone in the feature.

--

Added `datetime-utc` option in version 2.1.0.

**Comment by cdhowie** [comment]
> BTW, how do you create the date object? It is an interesting use case.

It is. Here's the basic idea. We want to allow a customer to edit a live video programming schedule, but when they schedule a video for 3PM, that's not a specific moment in UTC. Rather, it's 3PM in *every timezone*, which means that we don't actually care about the timezone of who is editing the schedule. Time zones are wholly irrelevant until the programming is *viewed*, and then we care about the timezone of the *viewer*.

The problem arises that `$http` converts dates to strings using `JSON.stringify()` which, while this does the right thing (converting local->UTC) in 99% of the cases, our case is the 1% where it's the wrong thing -- it converts to UTC and doesn't convey the local timezone offset, which means on the server end we get something like 7PM instead of 3PM, and no timezone information we could use to undo that conversion.

The best solution I can think of is to have all of the `Date` objects represented as though they were in UTC to the user, so when the conversion is applied we get the "right" data on the server end.  It's a hack, but there isn't much better a way of doing this with JS' obnoxious `Date` object.

**Comment by cdhowie** [comment]
Anyway, thanks very much for implementing this. I was going to take a stab at it myself and submit a pull request but you beat me to it. :+1:

**Comment by eight04** [comment]
IMAO, I will write a function to serialize the date object before sending through `$http` in such situation. Since the view value and model value doesn't match, it might have problem working with other date picker components.

If you are not going to use the date object but only sending them to server, you can try `datetime-model` option, which can convert the date object into string in any format you like. And since the conversion is done by the parser, the output value will match the user input. You also don't need to convert date string into date object when getting values from the server.

**Comment by cdhowie** [comment]
The date objects are used by other (custom) views that will expect them to be offset accordingly. It's not ideal, but forcing the objects to be "pre-serialized" seems like an even worse hack. I really wish `$http` would expose serialization functionality *by type* so that I could override how `Date` is handled without messing around with everything else. What I've come up with is an imperfect solution for an imperfect situation.

**Comment by eight04** [comment]
Fixed in 2.1.0.
