### ISSUE TITLE
Minify dist file

### ISSUE THREAD

**Issue by ericmdantas** [eight04/angular-datetime#14]
Is there any specific reason not to minify `dist/datime.js`?

If you guys want it, I can send a PR to do it.

Great module, by the way.

**Comment by eight04** [comment]
I think it's not that necessary to minify them because most of the developers have their own build tool, which not only minify js but concat each modules into one js file.

**Comment by ericmdantas** [comment]
Well, we could have both files, actually. A minified and a not minified one - which is pretty common.

But that's up to you.

**Comment by eight04** [comment]
It is good to have both :+1:

**Comment by ericmdantas** [comment]
I'll send a PR soon.

**Comment by eight04** [comment]
Fixed in 5.2.0.
