### ISSUE TITLE
date.getDate is not a function

### ISSUE THREAD

**Issue by rajeshwarpatlolla** [eight04/angular-datetime#15]
It is giving me error as shown below.

![screen shot 2016-01-19 at 12 54 58 am](https://cloud.githubusercontent.com/assets/9896335/12400668/7928fd3c-be47-11e5-8b7c-d8a21a779bde.png)

**Comment by eight04** [comment]
Looks like the date object is lack of `getDate` method. Check if the model is a Date object. Also, an example on [Plunker](https://plnkr.co/) would be nice :smiley:

**Comment by rajeshwarpatlolla** [comment]
I am passing date object itself.

**Comment by eight04** [comment]
Could you provide any source code?

**Comment by janhjordie** [comment]
It seems it's missing some timezone setup. I get the same error

**Comment by eight04** [comment]
Any example? https://plnkr.co/

**Comment by eight04** [comment]
BTW, there was no timezone option when this issue was created.

**Comment by janhjordie** [comment]
I figured it out. As usual it's date converting stuff. I got my date from a C# WebAPI, and I had to convert it to a real javascript date

 $scope.birthdate = moment($scope.user.birthdate).toDate();

**Comment by eight04** [comment]
If you like to use a string as the model value instead of Date object, try `datetime-model="format"`

**Comment by james-hoegerl** [comment]
Is there any way to make this play nice with momentjs?

**Comment by eight04** [comment]
I don't use momentjs. Any suggestion?

**Comment by james-hoegerl** [comment]
Yah I was thinking about it. Seems it would be a substantial rebuild. Ended
up finding a simpler directive that worked with it. But gosh yours is so
nice I was hoping for it to work as well. Thanks for the quick response.

**Comment by eight04** [comment]
Thanks for your appreciate. If you have some idea about how they should work together, feel free to create a new issue.

**Comment by alexander-d-com** [comment]
@james-hoegerl mind sharing it? i also get the date.getDate getting data from a c# webApi

**Comment by alexander-d-com** [comment]
Anyways, when getting the data from a controller simply calling 
`new Date($scope.theDate)` 
will resolve the issue

**Comment by eight04** [comment]
@james-hoegerl 

Starting from v5.0.0, the core parser and input mask are pulled out as [custom-input](https://github.com/eight04/custom-input). You might be interested to make it works with momentjs.
