### ISSUE TITLE
Demo Page Link Is Dead

### ISSUE THREAD

**Issue by PRISMAY** [eight04/angular-datetime#19]
The Demo link on the main info page is dead, i.e.,
https://rawgit.com/eight04/angular-datetime/master/demo.html

I wasn't sure who to contact regarding this so am submitting it as an issue here.  Thank you.

**Comment by PRISMAY** [comment]
Looks like it's due to the link using https rather than http.

**Comment by eight04** [comment]
![http://i.imgur.com/3ypQ8SA.png](http://i.imgur.com/3ypQ8SA.png)

Seems OK for me. Have you tried different browsers?
