### ISSUE TITLE
Deploy package to www.npmjs.com

### ISSUE THREAD

**Issue by baryr** [eight04/angular-datetime#28]
It would be nice if you could upload your package to www.npmjs.com.
Unfortunately the name is already taken (there is another package with the same name).

**Comment by eight04** [comment]
Seems we need to rewrite package.json. Any name suggestion?

**Comment by baryr** [comment]
Maybe angular-datetime-input ?

**Comment by eight04** [comment]
I tried updating package.json: https://github.com/eight04/angular-datetime/commit/e5c2f2faf5ade1b046952ab1df530448d3d7b182

I'm not sure how to make it become a valid node module. To add `var angular = require("angular")` at top of the dist file?

**Comment by eight04** [comment]
https://www.npmjs.com/package/angular
It says that we can use `require('angular')`, but I always get `ReferenceError: window is not defined`. Maybe it is OK to just mark "dist/datetime.js" as main file.

**Comment by eight04** [comment]
Fixed in 3.1.1. Please reopen this issue if I have done something wrong.
