### ISSUE TITLE
How to handle errors?

### ISSUE THREAD

**Issue by kino90** [eight04/angular-datetime#30]
Hi! Nice project! 
Is there a way to correctly handle the errors thrown by the plugin avoiding the output on the console?
How to do it?

Thanks

**Comment by eight04** [comment]
Do you mean the error logged by the directive?
https://github.com/eight04/angular-datetime/blob/master/src/directive.js#L294

It use $log service to log error. There is no official API to disable `$log.error` so you may have to make a decorator to control it.

But why do you want to disable the log? Is it better to disable it by the default?

**Comment by FranzSkuffka** [comment]
@kino90 did you find a solution?

**Comment by kino90** [comment]
@FranzSkuffka sadly we're not looking for that at the moment.. The project needs to go live soon, so we'll consider this minor issues in the future :) i'll let you know as soon as I'll look into it :)

**Comment by mackski** [comment]
Why not change this to log.debug? Then in production, console is clean.

**Comment by eight04** [comment]
The logging is removed at v5.0.0.
