### ISSUE TITLE
Slowdown and error when entering the date manually

### ISSUE THREAD

**Issue by macias** [eight04/angular-datetime#34]
Thank you very much for such a useful component! I have the problem though with the speed. Let's say I have such html code:

`<input type="text" datetime="yyyy-MM-dd" ng-model="start_date" ng-required="true"/>
`
When I use arrows to change the date, everything is fine. But let's say I have day "11" and I would like to manually write "21". So I type "21" and this is what happens:

* some heavy computation starts because there is no visual feedback, i.e. I don't see a number I just typed
* after some time I can see error in console:

```
[object Object] angular.min.js (line 117)
e/<()angular.min.js (line 117)
linkFunc/<()datetime.js (line 1177)
Pg</this.$$parseAndValidate()angular.min.js (line 285)
Pg</this.$commitViewValue()angular.min.js (line 284)
Pg</this.$$debounceViewValueCommit/<()angular.min.js (line 286)
vf/this.$get</m.prototype.$eval(a=Object { type="object"}, b=undefined)angular.min.js (line 145)
vf/this.$get</m.prototype.$apply(a=Object { type="object"})angular.min.js (line 145)
Pg</this.$$debounceViewValueCommit(b="input")angular.min.js (line 286)
Pg</this.$setViewValue(a="2016-07-1", b="input")angular.min.js (line 286)
lb/l(a="input")angular.min.js (line 176)
Sf(a=Object { type="object"}, b=Object { type="object"}, d=Object { type="object"})angular.min.js (line 37)
Rf/d(c=Object { type="object"}, d=undefined)angular.min.js (line 36)

```	
* "2" digit appears in the edit box
* "1" digit (which I typed initially) does NOT appear

* I can now type "1" and the processing of it is done in normal speed without any errors

**Comment by eight04** [comment]
Browser version?

**Comment by macias** [comment]
I am sorry for omitting it on report -- Firefox 47 (on openSUSE 13.2). Just for the record I also checked Chromium 51, there is also error, but more readable -- "NUMBER_TOOSHORT", and it is triggered for intermediate value "2" (of the day).

**Comment by eight04** [comment]
Can't reproduce with https://plnkr.co/edit/LQKuKc4lPFpKTOs4yMFw?p=preview.
Firefox 47.0.1, Windows 7.

Is it slow in other browsers too?

**Comment by macias** [comment]
No, so far I only encountered it in Firefox (and at my page, when I have more controls -- and also as I wrote only for this event, initial typing in two digits).

**Comment by eight04** [comment]
Does it happen on [plunker](https://plnkr.co/edit/LQKuKc4lPFpKTOs4yMFw?p=preview)?

If it works fine on the plunker, I guess there are some heavy calculation in your code which is triggered by *empty model*. That is, angular-datetime will set model to `undefined` when error occurs.

**Comment by macias** [comment]
Ok, so let's close this issue, and if I have more (hard -- i.e. convincing) data I will reopen this report. I hope it is OK with you.

Once again, thank you very much for the datetime and your help!
