### ISSUE TITLE
Binding keys to switch between parts of the date

### ISSUE THREAD

**Issue by wayjake** [eight04/angular-datetime#36]
This directive looks amazing. I wonder if it would be possible to bind the tab/space/enter key to move on to the next part of the date. It seems like that would make it just a little more intuitive.

**Comment by eight04** [comment]
Chrome use Tab/Shift-Tab for moving between different parts too. 👍 
But I don't think using space and enter is more intuitive, and enter is used to submit the form.

**Comment by wayjake** [comment]
Thank you for the response. Tab jumps from the current input to the next input. I would expect each date item either YY or DD or MM or whatever it is to be tab-able, so that when you tab to day then to month it then goes on the the next input in your form.

**Comment by eight04** [comment]
Why closing this? I think it is a good idea.

**Comment by wayjake** [comment]
Sorry that was an accident :)

**Comment by eight04** [comment]
https://rawgit.com/eight04/angular-datetime/dev-tab/example/demo.html

**Comment by wayjake** [comment]
Wow, flawless!!!!

**Comment by eight04** [comment]
Fixed in v4.0.0.
