### ISSUE TITLE
Input field is required

### ISSUE THREAD

**Issue by crazyjat** [eight04/angular-datetime#4]
Using the directive, datetime on an input type=text element, the element acts as if it is required and my form won't submit unless the field has a value. I need to be able to support and empty date input field.

**Comment by eight04** [comment]
I have pushed some commits: 
https://rawgit.com/eight04/angular-datetime/7d832aff970701c7a8733d7c8665adfbeba85ac8/demo.html

* Setting viewValue to "" will not raise parsing error if the field is not required.
* If the field is empty, restore last value on focus.
* Setting viewValue to "" will make modelValue become null.
* Setting modelValue to null will make viewValue become "".

**Comment by eight04** [comment]
Fixed in 1.3.0
