### ISSUE TITLE
Dynamically update view when model changes

### ISSUE THREAD

**Issue by Andrew-Lahikainen** [eight04/angular-datetime#40]
I've got a timer that updates the model each second, I've found that the view is not being updated when using this directive.

Is it possible to achieve this?

Here's a pen if needed http://codepen.io/Lahikainen/pen/WGmxPo

Thanks for the project, it's awesome!

**Comment by eight04** [comment]
You have to create a new Date object each time updating the model.
```
$ctrl.time.setSeconds($ctrl.time.getSeconds() + 1);
$ctrl.time = new Date($ctrl.time.getTime()); 
```
https://docs.angularjs.org/api/ng/directive/ngModel#complex-models-objects-or-collections-

**Comment by Andrew-Lahikainen** [comment]
Ah should have tried that!

Thanks heaps :)
