### ISSUE TITLE
Compatibility with Angular UI Bootstrap DatePicker Popup

### ISSUE THREAD

**Issue by crazyjat** [eight04/angular-datetime#46]
I need to be able to use your directive along with the angular ui bootstrap (https://angular-ui.github.io) DatePicker Popup. When I try, i get the following error:

### dateparser: baseDate is not a valid date
    (anonymous) @ angular.js:13920
    parse @ ui-bootstrap-tpls.js:1239
    parseDateString @ ui-bootstrap-tpls.js:3015
    parseDate @ ui-bootstrap-tpls.js:3042
    $$parseAndValidate @ angular.js:27647
    $commitViewValue @ angular.js:27637
    (anonymous) @ angular.js:27780
    $eval @ angular.js:17682
    $apply @ angular.js:17782
    $$debounceViewValueCommit @ angular.js:27779
    $setViewValue @ angular.js:27751
    (anonymous) @ datetime.js:419
    defaultHandlerWrapper @ angular.js:3497
    eventHandler @ angular.js:3485

Plunkr: https://plnkr.co/edit/Wg0kshnbFcMgZ5uKWiFt

**Comment by eight04** [comment]
https://plnkr.co/edit/7FsQbGTnAFxwD7cRBLK7?p=preview
This could be fixed by increasing the priority of datetime-input. Perhaps I can finish it in the next week.

**Comment by eight04** [comment]
Here is the fix:
https://github.com/eight04/angular-datetime/tree/dev-prior

I have forked your plunker with it:
https://plnkr.co/edit/4e6rkregI4zJ3hjywAno?p=preview

If there is not other problem, I will merge it these days.
