### ISSUE TITLE
Object.values

### ISSUE THREAD

**Issue by cht8687** [eight04/angular-datetime#50]
#Object.values is using in  [datetime.js](https://github.com/eight04/angular-datetime/blob/master/dist/datetime.js#L633)
Since it is an experimental [Object.values](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_objects/Object/values), it requires additional polyfil. 

I recommend use a polyfil function:

    var valuesPolyfill = function values (object) {
  		return Object.keys(object).map(key => object[key]);
	};

	var values = Object.values || valuesPolyfill;

I am happy to submit a PR is you like this. 
Cheers

**Comment by eight04** [comment]
I would like to stay with latest features. If you need to support older browsers, I suggest to use babel and babel-polyfill.

The demo also uses polyfill to run on IE8.
https://github.com/eight04/angular-datetime/blob/master/example/demo.html#L11

**Comment by cht8687** [comment]
ok, good to know that. cheers.
