### ISSUE TITLE
Placeholder isn't actually a placeholder and no way to turn it off

### ISSUE THREAD

**Issue by ChrisDerrig** [eight04/angular-datetime#51]
The placeholder uses the values from datetimePlaceholder, but actually puts them as text in the input, rather than in the placeholder= attribute, and so they are constantly there as a mask.  There's also no option to disable this behavior, so anytime the textbox gets cleared, it actually ends up with the tokens there again.

Ideally the placeholder should fill the placeholder attribute, and have an option to turn off the placeholder tokenizing (or at least a attribute to say that the text returned by getText() 'isPlaceholder')

**Comment by eight04** [comment]
`datetimePlaceholder` is not meant to replace `placeholder` attribute on `<input>` element. See https://github.com/eight04/angular-datetime/issues/39.

> they are constantly there as a mask. There's also no option to disable this behavior

Why would you want to turn off the mask?

> a attribute to say that the text returned by getText() 'isPlaceholder'

[`DatetimeParser.isEmpty()`](https://github.com/eight04/angular-datetime#datetimeparserisempty--boolean)

**Comment by ChrisDerrig** [comment]
The DateTimeParse.isEmpty() didn't seem to be firing when the field was empty, because the mask would fill the field.

The biggest reason for wanting to turn off the mask is Mobile. Text Masks on mobile can be frustrating.

The second is I open a calendar on ng-focus, so having the text there already which tries to match the token cause it to open, but then also to highlight the current token in the string, which I feel like messes with the UX.

Other than this mask/placeholder stuff, the plugin works great, I just can't use it as it is.

Thank you!

**Comment by eight04** [comment]
> The DateTimeParse.isEmpty() didn't seem to be firing when the field was empty, because the mask would fill the field.

`.isEmpty` is a method on a parser object. You can use it like:
```js
var parser = datetime("yyyy-MM-dd");
try {
	parser.parse("2017-06-(date)");
} catch (err) {
	console.log(err); // error: some nodes are empty
}
console.log(parser.getText(), parser.isInit(), parser.isEmpty());
// "2017-06-(date)" false false
```

> The biggest reason for wanting to turn off the mask is Mobile. Text Masks on mobile can be frustrating.

This is a problem. This directive was originally made for IE8, and I actually got some feedback that there are some other problems on mobiles (mostly with keyboard events).

> highlight the current token in the string

If you just don't want the user to select the text, you can try to `.blur()` the input in ng-focus handler.
