### ISSUE TITLE
strictdi error on version 5.1.3

### ISSUE THREAD

**Issue by Andrew-Lahikainen** [eight04/angular-datetime#57]
I'm getting the following error:
![screen shot 2017-09-14 at 2 46 53 pm](https://user-images.githubusercontent.com/10571313/30410023-b3b98790-995c-11e7-980e-7d301904c8a2.png)

It seems the package.json `main` property is pointing to a file that requires all the components of this package. Shouldn't this point to a transpiled version of your library? Otherwise I need to have babel and the ng-annotate plugin in order to use this.

If I import "angular-datetime-input/dist/datetime" directly I get this error:
 
![screen shot 2017-09-14 at 3 03 02 pm](https://user-images.githubusercontent.com/10571313/30410216-d9520ea4-995d-11e7-854e-607cb141f853.png)

Any way to resolve this?

**Comment by eight04** [comment]
This repository contains:

* source code
	- written with implicit DI notation
	- es6
* a pre-built dist, which is transpiled with
	- browserify
		- `custom-input` module is excluded from the build and shimmed with global variable `customInput`. You'll need to [import it manually](https://github.com/eight04/angular-datetime#installation)
	- babel (target IE8)
	- ng-annotate

You can resolve the second error by importing custom-input module manually.

For the first error, we should switch to explicit notation, however you still need to use babel if you want to transform es6 syntax.
