### ISSUE TITLE
Add bower support.

### ISSUE THREAD

**Issue by mominsamir** [eight04/angular-datetime#59]
Hi Nice work.

Please add bower support

**Comment by eight04** [comment]
I haven't used bower for a long time and npm supports flatten dependencies now. I think bower is able to install packages from github, if not, you may have to install the dist file directly.
```
bower install https://unpkg.com/angular-datetime-input@5.2.1/dist/datetime.js
```
If you want to switch to npm/yarn, there is an article on bower.io explaining how:
https://bower.io/blog/2017/how-to-migrate-away-from-bower/
