### ISSUE TITLE
Incorrect Year when using shortDate format

### ISSUE THREAD

**Issue by andreyjkee** [eight04/angular-datetime#61]
I have input with shortDate format, an initial state it has value 4/27/18 (in model I have "2018-04-27T11:25:43.322Z" at this moment), then I clear 18 (model is undefined now), unfocus from the item, and then I type 20, in model I have "0020-04-27T11:22:49.458Z" instead of "2020-04-27T11:22:49.458Z"
@eight04 could you look at this? Maybe some parsing problems take place

**Comment by eight04** [comment]
See [Known Issues section in the README](https://github.com/eight04/angular-datetime#known-issues). I don't think this is fixable.
