### ISSUE TITLE
Create a new version for angular 2+

### ISSUE THREAD

**Issue by maximepvrt** [eight04/angular-datetime#65]
Your directive is so cool 😍
I use it on all my angularJS projects, I want to do same on my new projects :-)

**Comment by eight04** [comment]
I have never used Angular 2+ before. Maybe someday, but I'm pretty sure it takes time. It would be nice if someone can help.

**Comment by AashishKJha** [comment]
@eight04 Hi, I am trying to create this directive in angular v7, I can feel it is taking lots of time to understand the code. But thanks a lot for such kind of easy directive.

**Comment by eight04** [comment]
You can check out [custom-input](https://github.com/eight04/custom-input) first. Basically, you have to:

1. Convert a date format definition string e.g. (`YYYY-mm-dd`) into a list of tokens that can be used by [TextParser](https://github.com/eight04/custom-input#textparser).
2. Extend/wrap the parser instance so it can store a timezone.
3. Bind the parser instance to the view by using [InputMask](https://github.com/eight04/custom-input#inputmask).

**Comment by eight04** [comment]
I wrote these stuff several years ago. Please tell me if the document is hard to understand.

**Comment by jsasmitha** [comment]
> @eight04 Hi, I am trying to create this directive in angular v7, I can feel it is taking lots of time to understand the code. But thanks a lot for such kind of easy directive.

Have u created a directive for angular v7?
