### ISSUE TITLE
Can't initialize control with anything but current date

### ISSUE THREAD

**Issue by bobweil** [eight04/angular-datetime#66]
When ng-model binds to a date value other than current date/time, the control displays current date/time instead.  If I change it at all, that changed value then overwrites my model.  How can I get the view to initialize with the value of ng-model?  This does the same on Chrome and IE11.

Hmm.  I noticed that in function createParser(format),  a property called TP is initialized with the current date.  If I change that to an arbitrary date in the code, that is the value that my control uses as the initial value.  It should initialize to the value of ng-model (a date object in my code).

Am I doing this wrong?  Not supposed to be binding to a date variable perhaps?

**Comment by eight04** [comment]
Please provide an example.

The min/max fields [in the demo](https://rawgit.com/eight04/angular-datetime/master/example/demo.html) also use different dates. Does it work for you?

**Comment by bobweil** [comment]
Thank you for your prompt reply.  I will work on an example.  I did try the min/max control and in fact I use the min and max. However, the problem is with two-way binding and that is not reflected there.  The initial value on that demo happens to be current date.  In my case, the initial value is from the database.  I display the database value in another <pre></pre> block and can see that it has been fetched, but the control displays current date instead.  If I change the value in the control, it updates the model variable, but I need it to come up initialized.   Thank you.

**Comment by bobweil** [comment]
Thanks again.  I forked your plunk and gradually added complexity to simulate my situation until it broke.  The attribute that broke it was the following:
`datetime-model="yyyy-MM-ddTHH:mm:ss"`

Broken plunk is at [https://next.plnkr.co/edit/vfZYi8Fhalto2oS7?preview](url)

This was existing code to which I was asked to add date validation to prevent errors.  The existing code used an earlier version of your module that did not seem to support min and max.  Should I just drop the datetime-model ?  I don't understand what it's for.

Best regards,
Bob

**Comment by eight04** [comment]
> datetime-model ? I don't understand what it's for.

The library assumes that `ng-model` is a JavaScript `Date` object. However, sometimes we would like to use a date string as the model so that it can be sent to the server without additional conversion.

By defining `datetime-model`, the directive would handle the conversion automatically, so you can use a date string as the `ng-model`.

**Comment by bobweil** [comment]
That explains it!  Thanks!  The previous developer was in fact passing a date string.  In seeking a solution to the validation request, I changed it to a Date object.  I appreciate your help very much.
