### ISSUE TITLE
Min/max validation doesn't update model value

### ISSUE THREAD

**Issue by eight04** [eight04/angular-datetime#7]
We often put validation in parser and formatter function. If validation failed, return undefined. This action let validation control model value directly. If we have to process validation outside parser/formatter function, then we cannot control model value anymore, which is the problem.

Currently I removed `return undefined` from min/max validator, which is breaking previous feature.

**Comment by eight04** [comment]
It's more reasonable that only parsing error will set model value to undefined.

**Comment by eight04** [comment]
@bkmediagroup-josh

**Comment by bkmediagroup-josh** [comment]
I returned undefined because un-setting the model value on failed validations seems to be a convention in angular. If there is a better place for that validation to live, I am all for moving it.

**Comment by eight04** [comment]
Starting from 1.3.0, there is a `$validate()` function in `ngModelController`, you can manually call that function to run validation. If the validation fails, angular will set the model value to undefined.

Here is how angular observe the min/max changes in `input[number]`:
https://github.com/angular/angular.js/blob/master/src/ng/directive/input.js#L1372-L1379
Angular will call `$validate()` each time the min/max value updated:
http://plnkr.co/edit/xAz9Lj50SszZCLJJjq17?p=preview
But we don't have this function in 1.2.x and validation only happens if view value is changed:
http://plnkr.co/edit/WLSzJkp9HvpRwls9DvvH?p=preview

Maybe we shouldn't observe min/max in 1.2.x.

**Comment by eight04** [comment]
Fixed in 2.0.0.

Keep the original behavior, which will set model value to undefined if min/max is not valid. Also add support for `$validators` in Angular 1.3.x:
https://github.com/eight04/angular-datetime/blob/master/src/directive.js#L320
