### ISSUE TITLE
Way to not localize?

### ISSUE THREAD

**Issue by mjortman** [eight04/angular-datetime#8]
Hi - Is there a way for me to have this NOT localize the time? I want it to just be used as a string, essentially. I got it to display correctly, but when I save the info, it is reverting to UTC again. I can't figure out a way to have it NOT localize on the save portion.

Thanks in advance.

**Comment by eight04** [comment]
An date object is always localized. You can get current offset by `date.getTimezoneOffset()`.

If you need UTC time, you can use `date.toUTCString()` for readable format, or `date.toISOString()` for ISO format. `toISOString()` is same as `toJSON()`, which is used in JSON conversion.

If you need local time, you can use `date.toString()` for readable format. If you need other formats, you can build a datetime parser yourself:
```
// MySQL format
var parser = datetime("yyyy-MM-dd HH:mm:ss");
parser.setDate(date).getText();

// ISO format
var parser = datetime("yyyy-MM-ddTHH:mm:ss.sssZ");
parser.setDate(date).getText();
```

**Comment by mjortman** [comment]
Thanks for the response! 

I was able to get what I wanted by changing every getX and setX (Hour, Minute, Month, etc) to getUTCX, and that worked perfectly.

Thanks very much for your work on this. I was having a whale of a time getting something to work to format dates and times both in a recent project, and this worked wonderfully. Thanks again!
